    - name: Barebones-Playbook
      hosts: debian-server
      gather_facts: yes
      vars_files: ./group_vars/variables.yml

      roles:
        - users-groups
        - packages
        - ssh
        - unattended-upgrades
        - mail
        - lynis
        - nftables
        - fail2ban

