    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install packages
      become: true
      apt:
        name: 
          - ca-certificates
          - curl
          - host
        state: present

